export const dataArray = [
    { 
      date: "11 Août 2023 6h", 
      distance: "28.8km", 
      duration: "0h28min",
      weatherIcon: "cloud-rain",
      timeIcon: "sun",
      start: "Impasse du champ du Bois, Mazé-Milon",
      end: "Rue des Capucins, Angers",
      mois: "Juin",
      bg: 7,
      bd: 0,
      cg: 8,
      cd: 0,
      rg: 1,
      rd: 0,
      campagne: 71,
      ville: 16,
      voieRapide: 9,
      autoroute: 3,
    },
    { 
      date: "29 Août 2023 16h", 
      distance: "709.8km", 
      duration: "8h56min",
      weatherIcon: "sun",
      timeIcon: "moon",
      start: "Impasse du champ du Bois, Mazé-Milon",
      end: "Rue des Capucins, Angers",
      mois: "Juillet",
      bg: 3,
      bd: 0,
      cg: 0,
      cd: 0,
      rg: 6,
      rd: 1,
      campagne: 71,
      ville: 16,
      voieRapide: 9,
      autoroute: 3,
    },
  ];
  